const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const cors=require('cors');
const multer=require('multer');
const path=require('path');
const fs=require('fs');
const crypto=require('crypto');
const {Pool}=require('pg');

const app=express();
const server=http.createServer(app);
const io=new Server(server,{cors:{origin:'*'}});
app.use(cors()); app.use(express.json({limit:'12mb'})); app.use(express.urlencoded({extended:true}));
const PUBLIC=path.join(__dirname,'public');
let DATA=process.env.DATA_DIR?path.resolve(process.env.DATA_DIR):path.join(__dirname,'data');
let UP=path.join(DATA,'uploads');
try{
  fs.mkdirSync(UP,{recursive:true});
}catch(e){
  console.warn('DATA_DIR unavailable:',DATA,e.code||e.message);
  DATA=path.join(__dirname,'data');
  UP=path.join(DATA,'uploads');
  fs.mkdirSync(UP,{recursive:true});
}
app.use(express.static(PUBLIC)); app.use('/uploads',express.static(UP));
const upload=multer({storage:multer.diskStorage({destination:UP,filename:(r,f,cb)=>cb(null,Date.now()+'-'+crypto.randomBytes(5).toString('hex')+path.extname(f.originalname||'.jpg'))}),limits:{fileSize:8*1024*1024}});
const ADMIN_LOGINS=['ыж'];
const MODES={"1v1":2,"2v2":4,"5v5":10};
const MAPS=['Sandstone','Breeze','Province','Rust','Dune','Hanami','Prison'];
const ROUNDS=[8,10,13,16];
const queues=Object.fromEntries(Object.keys(MODES).flatMap(m=>[`${m}_unranked`,`${m}_ranked`]).map(k=>[k,[]]));
let users={},parties={},matches=[],chat=[],privateMessages=[],reports=[],cancelRequests=[];
const sockets={}, socketUsers={};
const DATA_FILE=path.join(DATA,'legendpl-data.json');
let pool=null, dbReady=false;
if(process.env.DATABASE_URL){pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}})}
const clone=x=>JSON.parse(JSON.stringify(x));
const hash=p=>crypto.createHash('sha256').update(String(p)).digest('hex');
const uid=()=>Math.floor(100000+Math.random()*900000).toString();
const rid=(p='ID')=>p+'-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase();
function stats(){return {"1v1":{elo:100,matches:0,wins:0,losses:0,streak:0,bestStreak:0,kills:0,deaths:0,kd:0},"2v2":{elo:100,matches:0,wins:0,losses:0,streak:0,bestStreak:0,kills:0,deaths:0,kd:0},"5v5":{elo:100,matches:0,wins:0,losses:0,streak:0,bestStreak:0,kills:0,deaths:0,kd:0},totalWins:0,totalLosses:0,unrankedMatches1v1:0,unrankedMatches2v2:0,unrankedMatches5v5:0,matchHistory:[]};}
function level(e){e=Number(e)||100; return e>=2001?10:e>=1751?9:e>=1531?8:e>=1351?7:e>=1201?6:e>=1051?5:e>=901?4:e>=751?3:e>=501?2:1;}
function safe(id){const u=users[id]; if(!u)return null; return {id,username:u.username,inGameNick:u.inGameNick,inGameId:u.inGameId,isAdmin:!!u.isAdmin,avatar:u.stats?.avatar||'',sticker:u.stats?.sticker||'',friends:u.friends||[],pendingRequests:u.pendingRequests||[],stats:u.stats||stats()};}
function normalize(u){u.friends ||= [];u.pendingRequests ||= [];u.stats ||= stats();for(const m of Object.keys(MODES)){u.stats[m] ||= stats()[m];u.stats[m].elo=Math.max(100,Number(u.stats[m].elo)||100);u.stats[m].level=level(u.stats[m].elo)};u.stats.matchHistory ||= [];if(ADMIN_LOGINS.includes(String(u.username||'').toLowerCase()))u.isAdmin=true;return u;}
function snapshot(){return {users,parties,matches,chat,privateMessages,reports,cancelRequests,queues};}
async function persist(){try{if(pool&&dbReady){await pool.query('INSERT INTO legendpl_state(id,data) VALUES(1,$1) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data',[snapshot()]);}else{const t=DATA_FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(snapshot()));fs.renameSync(t,DATA_FILE)}}catch(e){console.error('persist',e.message)}}
async function load(){try{if(pool){await pool.query('CREATE TABLE IF NOT EXISTS legendpl_state(id integer primary key,data jsonb not null)');dbReady=true;const q=await pool.query('SELECT data FROM legendpl_state WHERE id=1');if(q.rows[0]?.data)Object.assign(globalState(q.rows[0].data));}else if(fs.existsSync(DATA_FILE))Object.assign(globalState(JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))));for(const u of Object.values(users))normalize(u);}catch(e){console.error('load',e.message)}}
function globalState(d){users=d.users||{};parties=d.parties||{};matches=d.matches||d.pendingMatches||[];chat=d.chat||d.chatMessages||[];privateMessages=d.privateMessages||[];reports=d.reports||[];cancelRequests=d.cancelRequests||[];for(const k of Object.keys(queues))queues[k]=[];return d;}
function partyOf(id){return Object.entries(parties).find(([,p])=>p.members.includes(id));}
function partyPayload(id){const p=parties[id];return p?{id,code:p.code,leaderId:p.leaderId,members:p.members.map(safe).filter(Boolean)}:null;}
function send(id,event,data){if(sockets[id])io.to(sockets[id]).emit(event,data)}
function broadcastParty(id){const p=parties[id];if(!p)return;for(const m of p.members)send(m,'partyUpdate',partyPayload(id))}
function queueCount(k){return queues[k].reduce((n,g)=>n+g.userIds.length,0)}
function queueState(){const o={};for(const m of Object.keys(MODES))o[m]={unranked:queueCount(`${m}_unranked`),ranked:queueCount(`${m}_ranked`)};return o}
function queueMembership(id){const out={};for(const m of Object.keys(MODES)){for(const ranked of [false,true]){const k=`${m}_${ranked?'ranked':'unranked'}`;out[k]=queues[k].some(g=>g.userIds.includes(id));}}return out}
function broadcastQueue(){io.emit('queueUpdate',queueState());for(const id of Object.keys(sockets))send(id,'queueMembership',queueMembership(id))}
function rankedAllowed(id,mode){return Number(users[id]?.stats?.[`unrankedMatches${mode}`]||0)>=3}
function findMatch(mode,ranked){const k=`${mode}_${ranked?'ranked':'unranked'}`, need=MODES[mode];let total=0,sel=[];for(const g of queues[k]){if(total+g.userIds.length<=need){sel.push(g);total+=g.userIds.length}if(total===need)break}if(total!==need)return null;const ids=sel.flatMap(g=>g.userIds);queues[k]=queues[k].filter(g=>!sel.includes(g));return ids}
function makeMatch(mode,ranked,ids){const shuffled=clone(ids).sort(()=>Math.random()-.5);const half=shuffled.length/2;const match={id:rid('MATCH'),mode,ranked,participants:shuffled,teamT:shuffled.slice(0,half),teamCT:shuffled.slice(half),accepted:[],status:'waiting_accept',createdAt:Date.now(),mapVotes:{},roundVotes:{},screenshots:[],resolved:false};matches.push(match);persist();for(const id of ids)send(id,'matchFound',publicMatch(match));setTimeout(()=>timeoutMatch(match.id),20000);return match}
function publicMatch(m){return {matchId:m.id,id:m.id,mode:m.mode,ranked:m.ranked,accepted:m.accepted.length,total:m.participants.length,timeout:Math.max(0,20-Math.floor((Date.now()-m.createdAt)/1000)),participants:m.participants.map(safe).filter(Boolean),mapOptions:MAPS,roundOptions:ROUNDS}}
function timeoutMatch(id){const m=matches.find(x=>x.id===id);if(!m||m.status!=='waiting_accept')return;m.status='cancelled';m.cancelReason='Не все игроки подтвердили матч за 20 секунд.';for(const u of m.participants)send(u,'matchCancelled',{matchId:id,reason:m.cancelReason});persist()}
function startDraft(m){m.status='draft';m.draft={mapVotes:{},roundVotes:{},expiresAt:Date.now()+20000};for(const u of m.participants)send(u,'draftStart',{matchId:m.id,mapOptions:MAPS,roundOptions:ROUNDS,mapVotes:m.mapVotes,roundVotes:m.roundVotes,seconds:20});setTimeout(()=>finishDraft(m.id),20000);persist()}
function finishDraft(id){const m=matches.find(x=>x.id===id);if(!m||m.status!=='draft')return;const pick=(votes,opts)=>{let best=opts[0],max=-1;for(const o of opts){const n=Object.values(votes).filter(v=>v===o).length;if(n>max){max=n;best=o}}return best};m.map=pick(m.mapVotes,MAPS);m.rounds=pick(m.roundVotes,ROUNDS);m.maxMoney=16000;m.status='awaiting_result';m.captains=[m.teamT[Math.floor(Math.random()*m.teamT.length)],m.teamCT[Math.floor(Math.random()*m.teamCT.length)]];for(const u of m.participants)send(u,'matchLobby',lobby(m));persist()}
function lobby(m){return {matchId:m.id,mode:m.mode,ranked:m.ranked,map:m.map,rounds:m.rounds,maxMoney:16000,captains:m.captains.map(safe),teamT:m.teamT.map(safe),teamCT:m.teamCT.map(safe),screenshots:m.screenshots}}
function resolve(m,winner,changes){if(m.resolved)return {ok:false,msg:'Матч уже обработан.'};if(!m.screenshots.length)return {ok:false,msg:'Нужен скриншот результата.'};if(!['T','CT'].includes(winner))return {ok:false,msg:'Неверная команда.'};for(const id of m.participants){const u=users[id];if(!u)continue;const s=u.stats[m.mode],won=(winner==='T'?m.teamT:m.teamCT).some(x=>x===id);s.matches++;if(won){s.wins++;s.streak++;s.bestStreak=Math.max(s.bestStreak,s.streak);u.stats.totalWins++;}else{s.losses++;s.streak=0;u.stats.totalLosses++;}const d=Number(changes?.[id]||0);s.elo=Math.max(100,s.elo+(Number.isFinite(d)?Math.trunc(d):0));s.level=level(s.elo);if(!m.ranked)u.stats[`unrankedMatches${m.mode}`]++;u.stats.matchHistory.unshift({matchId:m.id,mode:m.mode,ranked:m.ranked,map:m.map,rounds:m.rounds,winnerTeam:winner,won,eloDelta:Number.isFinite(d)?Math.trunc(d):0,eloAfter:s.elo,timestamp:Date.now()});u.stats.matchHistory=u.stats.matchHistory.slice(0,100)}m.resolved=true;m.status='resolved';m.winnerTeam=winner;m.eloChanges=changes||{};m.resolvedAt=Date.now();for(const id of m.participants)send(id,'matchResolved',{matchId:m.id,winnerTeam:winner,eloChanges:m.eloChanges,user:safe(id)});persist();return {ok:true}}

app.post('/api/register',async(req,res)=>{const {username,password,inGameNick,inGameId}=req.body||{};if(!username||!password||!inGameNick||!inGameId)return res.status(400).json({success:false,message:'Заполните все поля.'});if(Object.values(users).some(u=>u.username.toLowerCase()===String(username).trim().toLowerCase()))return res.status(409).json({success:false,message:'Такой логин уже занят.'});const id=uid();users[id]=normalize({username:String(username).trim(),password:hash(password),inGameNick:String(inGameNick).trim(),inGameId:String(inGameId).trim(),isAdmin:ADMIN_LOGINS.includes(String(username).trim().toLowerCase()),stats:stats(),friends:[],pendingRequests:[],createdAt:Date.now()});await persist();res.json({success:true,message:'Регистрация успешна. Теперь войдите.',user:safe(id)})});
app.post('/api/login',async(req,res)=>{const {username,password}=req.body||{};const e=Object.entries(users).find(([,u])=>u.username.toLowerCase()===String(username||'').trim().toLowerCase());if(!e||e[1].password!==hash(password))return res.status(401).json({success:false,message:'Неверный логин или пароль.'});normalize(e[1]);await persist();res.json({success:true,message:'Вход выполнен.',user:safe(e[0]),party:partyOf(e[0])?partyPayload(partyOf(e[0])[0]):null})});
app.get('/api/me',(req,res)=>{const u=safe(req.query.userId);if(!u)return res.status(401).json({success:false,message:'Сессия недействительна.'});const p=partyOf(u.id);res.json({success:true,user:u,party:p?partyPayload(p[0]):null})});
app.get('/api/user/:id',(req,res)=>{const u=safe(req.params.id);u?res.json({success:true,user:u}):res.status(404).json({success:false,message:'Игрок не найден.'})});
app.get('/api/search-users',(req,res)=>{const q=String(req.query.q||'').toLowerCase();res.json({success:true,users:Object.entries(users).filter(([id,u])=>id.includes(q)||u.username.toLowerCase().includes(q)||u.inGameNick.toLowerCase().includes(q)||u.inGameId.toLowerCase().includes(q)).slice(0,30).map(([id])=>safe(id))})});
app.post('/api/friend-request',async(req,res)=>{const {fromUserId,toUserId}=req.body;const a=users[fromUserId],b=users[toUserId];if(!a||!b||fromUserId===toUserId)return res.status(400).json({success:false,message:'Игрок не найден или указан неверно.'});if(a.friends.includes(toUserId))return res.status(400).json({success:false,message:'Вы уже друзья.'});if(!b.pendingRequests.includes(fromUserId))b.pendingRequests.push(fromUserId);await persist();send(toUserId,'friendRequest',{user:safe(fromUserId)});res.json({success:true})});
app.post('/api/friend-accept',async(req,res)=>{const {userId,friendId}=req.body;if(!users[userId]||!users[friendId])return res.status(404).json({success:false});users[userId].pendingRequests=users[userId].pendingRequests.filter(x=>x!==friendId);if(!users[userId].friends.includes(friendId))users[userId].friends.push(friendId);if(!users[friendId].friends.includes(userId))users[friendId].friends.push(userId);await persist();send(friendId,'friendChanged',{});res.json({success:true})});
app.post('/api/friend-reject',async(req,res)=>{const {userId,friendId}=req.body;if(users[userId])users[userId].pendingRequests=users[userId].pendingRequests.filter(x=>x!==friendId);await persist();res.json({success:true})});
app.get('/api/friends',(req,res)=>{const u=users[req.query.userId];if(!u)return res.status(404).json({success:false});res.json({success:true,friends:u.friends.map(safe).filter(Boolean),requests:u.pendingRequests.map(safe).filter(Boolean)})});
app.get('/api/private-messages',(req,res)=>{const id=String(req.query.userId||'');if(!users[id])return res.status(404).json({success:false,message:'Игрок не найден.'});res.json({success:true,messages:privateMessages.filter(m=>m.from===id||m.to===id).slice(-1000)})});
app.post('/api/create-party',async(req,res)=>{const {userId}=req.body;if(!users[userId])return res.status(404).json({success:false});const p=partyOf(userId);if(p)return res.json({success:false,party:partyPayload(p[0]),message:'Вы уже в пати.'});const id=rid('PARTY');parties[id]={code:id,leaderId:userId,members:[userId],createdAt:Date.now()};await persist();res.json({success:true,party:partyPayload(id)})});
app.post('/api/join-party',async(req,res)=>{const {userId,partyId}=req.body;const p=parties[partyId];if(!p)return res.status(404).json({success:false,message:'Пати не найдена.'});if(p.members.length>=5)return res.status(400).json({success:false,message:'Пати заполнена.'});if(!p.members.includes(userId))p.members.push(userId);await persist();broadcastParty(partyId);res.json({success:true,party:partyPayload(partyId)})});
app.post('/api/leave-party',async(req,res)=>{const {userId,partyId}=req.body;const p=parties[partyId];if(!p)return res.json({success:true});p.members=p.members.filter(x=>x!==userId);if(!p.members.length)delete parties[partyId];else{if(p.leaderId===userId)p.leaderId=p.members[0];broadcastParty(partyId)}await persist();res.json({success:true})});
app.post('/api/invite-party',async(req,res)=>{const {fromUserId,targetUserId}=req.body;const p=partyOf(fromUserId);if(!p)return res.status(400).json({success:false,message:'Сначала создайте пати.'});send(targetUserId,'partyInvite',{partyId:p[0],fromName:users[fromUserId]?.inGameNick||'Игрок'});res.json({success:true})});
app.post('/api/report',async(req,res)=>{const {reporterId,targetId,reason}=req.body;if(!users[reporterId]||!users[targetId])return res.status(404).json({success:false,message:'Игрок не найден.'});if(!['Токсичность','Читы','Багаюз'].includes(reason))return res.status(400).json({success:false,message:'Выберите причину.'});const r={id:rid('REP'),reporterId,targetId,reason,status:'open',createdAt:Date.now()};reports.unshift(r);await persist();res.json({success:true,reportId:r.id})});
app.post('/api/upload-avatar',upload.single('avatar'),async(req,res)=>{if(!users[req.body.userId])return res.status(404).json({success:false});if(!req.file)return res.status(400).json({success:false,message:'Файл не выбран.'});users[req.body.userId].stats.avatar='/uploads/'+req.file.filename;await persist();send(req.body.userId,'userUpdated',safe(req.body.userId));res.json({success:true,avatar:users[req.body.userId].stats.avatar})});
app.post('/api/change-nick',async(req,res)=>{const {userId,newNick}=req.body;if(!users[userId])return res.status(404).json({success:false});users[userId].inGameNick=String(newNick||'').trim().slice(0,32);await persist();res.json({success:true,user:safe(userId)})});
app.get('/api/top',(req,res)=>{const mode=MODES[req.query.mode]?req.query.mode:'1v1';res.json({success:true,users:Object.entries(users).map(([id])=>{const u=safe(id);return {...u,elo:u.stats[mode].elo,wins:u.stats[mode].wins,level:u.stats[mode].level}}).sort((a,b)=>b.elo-a.elo).slice(0,100)})});
app.post('/api/match/:id/screenshot',upload.single('screenshot'),async(req,res)=>{const m=matches.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({success:false,message:'Матч не найден.'});if(!m.participants.includes(req.body.userId))return res.status(403).json({success:false});if(!req.file)return res.status(400).json({success:false,message:'Скриншот не выбран.'});const s={id:rid('SHOT'),userId:req.body.userId,nickname:users[req.body.userId].inGameNick,url:'/uploads/'+req.file.filename,timestamp:Date.now()};m.screenshots.push(s);await persist();for(const u of m.participants)send(u,'screenshotAdded',{matchId:m.id,screenshot:s});res.json({success:true,screenshot:s})});
app.post('/api/match/:id/cancel-request',async(req,res)=>{const m=matches.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({success:false,message:'Матч не найден.'});const r={id:rid('CANCEL'),matchId:m.id,userId:req.body.userId,reason:String(req.body.reason||'Не могу зайти в игру').slice(0,300),status:'open',createdAt:Date.now()};cancelRequests.unshift(r);await persist();res.json({success:true,requestId:r.id})});
app.post('/api/admin/match/:id/cancel',async(req,res)=>{if(!users[req.body.adminId]?.isAdmin)return res.status(403).json({success:false,message:'Нет доступа.'});const m=matches.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({success:false});if(m.status==='resolved')return res.status(400).json({success:false,message:'Матч уже завершён.'});m.status='cancelled';m.cancelReason=String(req.body.reason||'Матч отменён администратором');for(const u of m.participants)send(u,'matchCancelled',{matchId:m.id,reason:m.cancelReason});await persist();res.json({success:true})});
app.post('/api/admin/cancel-request/:id',async(req,res)=>{if(!users[req.body.adminId]?.isAdmin)return res.status(403).json({success:false});const r=cancelRequests.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({success:false});r.status=req.body.status==='approved'?'approved':'rejected';if(r.status==='approved'){const m=matches.find(x=>x.id===r.matchId);if(m){m.status='cancelled';m.cancelReason='Отмена по заявке игрока, подтверждена администратором.';for(const u of m.participants)send(u,'matchCancelled',{matchId:m.id,reason:m.cancelReason})}}await persist();res.json({success:true})});
function admin(req,res){if(!users[req.query.adminId||req.body.adminId]?.isAdmin){res.status(403).json({success:false,message:'Недостаточно прав.'});return null}return true}
app.get('/api/check-admin',(req,res)=>res.json({isAdmin:!!users[req.query.userId]?.isAdmin}));
app.get('/api/admin/stats',(req,res)=>{if(!admin(req,res))return;res.json({success:true,online:Object.keys(sockets).length,users:Object.keys(users).length,matches:matches.length,reports:reports.filter(x=>x.status==='open').length,cancelRequests:cancelRequests.filter(x=>x.status==='open').length})});
app.get('/api/admin/users',(req,res)=>{if(!admin(req,res))return;res.json({success:true,users:Object.entries(users).map(([id])=>safe(id))})});
app.get('/api/admin/reports',(req,res)=>{if(!admin(req,res))return;res.json({success:true,reports:reports.map(r=>({...r,reporter:safe(r.reporterId),target:safe(r.targetId)}))})});
app.get('/api/admin/cancel-requests',(req,res)=>{if(!admin(req,res))return;res.json({success:true,requests:cancelRequests.map(r=>({...r,user:safe(r.userId),match:matches.find(m=>m.id===r.matchId)}))})});
app.get('/api/admin/matches',(req,res)=>{if(!admin(req,res))return;res.json({success:true,matches:matches.filter(m=>m.status!=='cancelled').map(m=>({...m,participants:m.participants.map(safe),teamT:m.teamT.map(safe),teamCT:m.teamCT.map(safe)}))})});
app.post('/api/admin/report/:id',async(req,res)=>{if(!admin(req,res))return;const r=reports.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({success:false});r.status=req.body.status==='closed'?'closed':'open';r.adminId=req.body.adminId;await persist();res.json({success:true})});
app.post('/api/admin/match/:id/resolve',async(req,res)=>{if(!admin(req,res))return;const m=matches.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({success:false});const r=resolve(m,req.body.winnerTeam,req.body.eloChanges||{});if(!r.ok)return res.status(400).json({success:false,message:r.msg});res.json({success:true})});
app.post('/api/admin/action',async(req,res)=>{if(!admin(req,res))return;const u=users[req.body.targetUserId];if(!u||u.isAdmin)return res.status(400).json({success:false,message:'Нельзя применить действие.'});const h=Math.max(1,Number(req.body.hours||24))*3600000;if(req.body.action==='ban')u.ban={until:Date.now()+h,reason:req.body.reason||''};if(req.body.action==='mute')u.mute={until:Date.now()+h,reason:req.body.reason||''};await persist();res.json({success:true})});

io.on('connection',socket=>{socket.on('auth',id=>{if(!users[id])return;sockets[id]=socket.id;socketUsers[socket.id]=id;send(id,'queueUpdate',queueState());send(id,'queueMembership',queueMembership(id));send(id,'chatHistory',chat.slice(-100));send(id,'privateHistory',privateMessages.filter(m=>m.from===id||m.to===id).slice(-1000));const p=partyOf(id);if(p)send(id,'partyUpdate',partyPayload(p[0]));for(const m of matches.filter(x=>x.participants.includes(id)&&!['resolved','cancelled'].includes(x.status))){if(m.status==='waiting_accept')send(id,'matchFound',publicMatch(m));if(m.status==='draft')send(id,'draftStart',{matchId:m.id,mapOptions:MAPS,roundOptions:ROUNDS,mapVotes:m.mapVotes,roundVotes:m.roundVotes,seconds:Math.max(1,Math.ceil((m.draft.expiresAt-Date.now())/1000))});if(m.status==='awaiting_result')send(id,'matchLobby',lobby(m));}});
socket.on('joinQueue',async({mode,ranked,partyId})=>{const id=socketUsers[socket.id];if(!id||!MODES[mode])return;const p=partyId&&parties[partyId]&&parties[partyId].members.includes(id)?parties[partyId]:null;const ids=p?p.members.slice():[id];if(ranked&&ids.some(x=>!rankedAllowed(x,mode))){send(id,'queueError',{message:`Нельзя играть в ранговый режим: сыграйте 3 обычных матча в режиме ${mode}.`});return}const k=`${mode}_${ranked?'ranked':'unranked'}`;if(!queues[k].some(g=>g.userIds.some(x=>ids.includes(x))))queues[k].push({userIds:ids,createdAt:Date.now()});broadcastQueue();const found=findMatch(mode,ranked);if(found)makeMatch(mode,ranked,found);broadcastQueue();await persist()});
socket.on('leaveQueue',async({mode,ranked})=>{const id=socketUsers[socket.id];if(!id)return;const k=`${mode}_${ranked?'ranked':'unranked'}`;queues[k]=queues[k].filter(g=>!g.userIds.includes(id));broadcastQueue();await persist()});
socket.on('acceptMatch',async({matchId})=>{const id=socketUsers[socket.id],m=matches.find(x=>x.id===matchId);if(!m||m.status!=='waiting_accept'||!m.participants.includes(id))return;if(!m.accepted.includes(id))m.accepted.push(id);for(const u of m.participants)send(u,'matchAcceptedUpdate',{matchId,accepted:m.accepted.length,total:m.participants.length});if(m.accepted.length===m.participants.length)startDraft(m);await persist()});
socket.on('declineMatch',async({matchId})=>{const id=socketUsers[socket.id],m=matches.find(x=>x.id===matchId);if(!m||!m.participants.includes(id))return;m.status='cancelled';m.cancelReason='Игрок отказался от матча.';for(const u of m.participants)send(u,'matchCancelled',{matchId,reason:m.cancelReason});await persist()});
socket.on('draftVote',async({matchId,map,rounds})=>{const id=socketUsers[socket.id],m=matches.find(x=>x.id===matchId);if(!m||m.status!=='draft'||!m.participants.includes(id))return;if(MAPS.includes(map))m.mapVotes[id]=map;if(ROUNDS.includes(Number(rounds)))m.roundVotes[id]=Number(rounds);for(const u of m.participants)send(u,'draftUpdate',{matchId,mapVotes:m.mapVotes,roundVotes:m.roundVotes});if(Object.keys(m.mapVotes).length>=m.participants.length&&Object.keys(m.roundVotes).length>=m.participants.length)finishDraft(matchId);await persist()});
socket.on('partyInviteAccept',async({partyId})=>{const id=socketUsers[socket.id],p=parties[partyId];if(!id||!p||p.members.length>=5)return;if(!p.members.includes(id))p.members.push(id);await persist();broadcastParty(partyId)});
socket.on('chatMessage',async msg=>{const id=socketUsers[socket.id];if(!id)return;let text=typeof msg==='object'?(msg.text||''):String(msg||'');text=text.trim().slice(0,500);if(!text)return;const m={id:rid('MSG'),userId:id,nickname:users[id].inGameNick,avatar:users[id].stats.avatar,isAdmin:!!users[id].isAdmin,sticker:users[id].stats.sticker,text,timestamp:Date.now()};chat.push(m);chat=chat.slice(-500);io.emit('chatMessage',m);await persist()});
socket.on('privateMessage',async({toUserId,text})=>{const from=socketUsers[socket.id];if(!from||!users[toUserId])return;const m={id:rid('PM'),from,to:toUserId,text:String(text||'').trim().slice(0,500),timestamp:Date.now()};if(!m.text)return;privateMessages.push(m);privateMessages=privateMessages.slice(-1000);send(from,'privateMessage',m);send(toUserId,'privateMessage',m);await persist()});
socket.on('disconnect',()=>{const id=socketUsers[socket.id];if(id&&sockets[id]===socket.id)delete sockets[id];delete socketUsers[socket.id]})});
load().then(()=>server.listen(process.env.PORT||3000,()=>{console.log('Legend Pl server started');if(!process.env.DATABASE_URL)console.warn('DATABASE_URL is not set: Render ephemeral storage will not survive restarts. Set DATABASE_URL to Render PostgreSQL or DATA_DIR to a persistent disk.')}));
