const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const cors=require('cors');
const multer=require('multer');
const path=require('path');
const fs=require('fs');
const crypto=require('crypto');
const {Pool}=require('pg');

const app=express();
const server=http.createServer(app);
const io=new Server(server,{cors:{origin:'*'}});
app.use(cors()); app.use(express.json({limit:'12mb'})); app.use(express.urlencoded({extended:true}));
const PUBLIC=path.join(__dirname,'public');
let DATA=process.env.DATA_DIR?path.resolve(process.env.DATA_DIR):path.join(__dirname,'data');
let UP=path.join(DATA,'uploads');
try{
  fs.mkdirSync(UP,{recursive:true});
}catch(e){
  console.warn('DATA_DIR unavailable:',DATA,e.code||e.message);
  DATA=path.join(__dirname,'data');
  UP=path.join(DATA,'uploads');
  fs.mkdirSync(UP,{recursive:true});
}
app.use(express.static(PUBLIC)); app.use('/uploads',express.static(UP));
const upload=multer({storage:multer.diskStorage({destination:UP,filename:(r,f,cb)=>cb(null,Date.now()+'-'+crypto.randomBytes(5).toString('hex')+path.extname(f.originalname||'.jpg'))}),limits:{fileSize:8*1024*1024}});
const ADMIN_LOGINS=['ыж','ыж1'];
const MODES={"1v1":2,"2v2":4,"5v5":10};
const LEAGUES={pc:'PC лига',phone:'Phone лига'};
const MAPS=['Sandstone','Breeze','Province','Rust','Dune','Hanami','Prison'];
const ROUNDS=[8,10,13,16];
const queues=Object.fromEntries(Object.keys(LEAGUES).flatMap(l=>Object.keys(MODES).flatMap(m=>[`${l}_${m}_unranked`,`${l}_${m}_ranked`])).map(k=>[k,[]]));
let users={},parties={},matches=[],chat=[],privateMessages=[],reports=[],cancelRequests=[];
const sockets={}, socketUsers={};
const DATA_FILE=path.join(DATA,'legendpl-data.json');
let pool=null, dbReady=false;
if(process.env.DATABASE_URL){pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}})}
const clone=x=>JSON.parse(JSON.stringify(x));
const hash=p=>crypto.createHash('sha256').update(String(p)).digest('hex');
const uid=()=>Math.floor(100000+Math.random()*900000).toString();
const rid=(p='ID')=>p+'-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase();
function stats(){return {"1v1":{elo:100,matches:0,wins:0,losses:0,streak:0,bestStreak:0,kills:0,deaths:0,kd:0},"2v2":{elo:100,matches:0,wins:0,losses:0,streak:0,bestStreak:0,kills:0,deaths:0,kd:0},"5v5":{elo:100,matches:0,wins:0,losses:0,streak:0,bestStreak:0,kills:0,deaths:0,kd:0},totalWins:0,totalLosses:0,unrankedMatches1v1:0,unrankedMatches2v2:0,unrankedMatches5v5:0,matchHistory:[]};}
function level(e){e=Number(e)||100; return e>=2001?10:e>=1751?9:e>=1531?8:e>=1351?7:e>=1201?6:e>=1051?5:e>=901?4:e>=751?3:e>=501?2:1;}
function avatarValue(u){const a=u?.stats?.avatar||'';if(!a)return '';if(a.startsWith('data:image/'))return a;if(a.startsWith('/uploads/')){const f=path.join(UP,path.basename(a));return fs.existsSync(f)?a:'';}return a;}
function activeRestriction(u,key){const r=u?.[key];if(!r)return null;if(Number(r.until||0)>Date.now())return r;try{delete u[key]}catch{}return null;}
function banMessage(u){const r=activeRestriction(u,'ban');if(!r)return null;return `Вы забанены до ${new Date(r.until).toLocaleString('ru-RU')}. Причина: ${r.reason||'не указана'}`;}
function muteMessage(u){const r=activeRestriction(u,'mute');if(!r)return null;const mins=Math.max(1,Math.ceil((r.until-Date.now())/60000));return `Вы не можете писать в чаты ещё ${mins} мин. Причина: ${r.reason||'не указана'}`;}
function disconnectUser(id,event,data){if(sockets[id]){send(id,event,data);const sid=sockets[id];delete sockets[id];delete socketUsers[sid];const ss=io.sockets.sockets.get(sid);if(ss)try{ss.disconnect(true)}catch{}}}
function resultEditAllowed(m){return !!m?.resolvedAt&&Date.now()-Number(m.resolvedAt)<=3*60*60*1000;}
function recalcUserDerived(u,mode){const hist=(u.stats.matchHistory||[]).filter(x=>x.mode===mode).sort((a,b)=>(a.timestamp||0)-(b.timestamp||0));const st=u.stats[mode]||{};st.matches=hist.length;st.wins=hist.filter(x=>x.won).length;st.losses=hist.filter(x=>!x.won).length;let streak=0,best=0;for(const h of hist){if(h.won){streak++;best=Math.max(best,streak)}else streak=0}st.streak=streak;st.bestStreak=best;let elo=100;for(const h of hist){elo=Math.max(0,elo+Number(h.eloDelta||0));h.eloAfter=elo}st.elo=elo;st.level=level(elo);u.stats.totalWins=Object.keys(MODES).reduce((n,m)=>n+(u.stats[m]?.wins||0),0);u.stats.totalLosses=Object.keys(MODES).reduce((n,m)=>n+(u.stats[m]?.losses||0),0);u.stats[`unrankedMatches${mode}`]=hist.filter(x=>!x.ranked).length;}
function rollbackResolvedResult(m){for(const id of m.participants){const u=users[id];if(!u)continue;u.stats.matchHistory=(u.stats.matchHistory||[]).filter(h=>h.matchId!==m.id);recalcUserDerived(u,m.mode)}m.resolved=false;m.resolvedAt=null;m.winnerTeam=null;m.eloChanges={};}
function safe(id){const u=users[id]; if(!u)return null; return {id,username:u.username,inGameNick:u.inGameNick,inGameId:u.inGameId,isAdmin:!!u.isAdmin||ADMIN_LOGINS.includes(String(u.username||'').toLowerCase()),avatar:avatarValue(u),sticker:u.stats?.sticker||'',friends:u.friends||[],pendingRequests:u.pendingRequests||[],ban:activeRestriction(u,'ban'),mute:activeRestriction(u,'mute'),stats:u.stats||stats()};}
function normalize(u){u.friends ||= [];u.pendingRequests ||= [];u.stats ||= stats();for(const m of Object.keys(MODES)){u.stats[m] ||= stats()[m];const ev=Number(u.stats[m].elo);u.stats[m].elo=Math.max(0,Number.isFinite(ev)?ev:100);u.stats[m].level=level(u.stats[m].elo)};u.stats.matchHistory ||= [];if(ADMIN_LOGINS.includes(String(u.username||'').toLowerCase()))u.isAdmin=true;return u;}
function snapshot(){return {users,parties,matches,chat,privateMessages,reports,cancelRequests,queues};}
async function persist(){try{if(pool&&dbReady){await pool.query('INSERT INTO legendpl_state(id,data) VALUES(1,$1) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data',[snapshot()]);}else{const t=DATA_FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(snapshot()));fs.renameSync(t,DATA_FILE)}}catch(e){console.error('persist',e.message)}}
async function load(){try{if(pool){await pool.query('CREATE TABLE IF NOT EXISTS legendpl_state(id integer primary key,data jsonb not null)');dbReady=true;const q=await pool.query('SELECT data FROM legendpl_state WHERE id=1');if(q.rows[0]?.data)Object.assign(globalState(q.rows[0].data));}else if(fs.existsSync(DATA_FILE))Object.assign(globalState(JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))));for(const u of Object.values(users))normalize(u);}catch(e){console.error('load',e.message)}}
function globalState(d){users=d.users||{};parties=d.parties||{};matches=d.matches||d.pendingMatches||[];chat=d.chat||d.chatMessages||[];privateMessages=d.privateMessages||[];reports=d.reports||[];cancelRequests=d.cancelRequests||[];for(const k of Object.keys(queues))queues[k]=[];return d;}
function partyOf(id){return Object.entries(parties).find(([,p])=>p.members.includes(id));}
function partyPayload(id){const p=parties[id];return p?{id,code:p.code,leaderId:p.leaderId,members:p.members.map(safe).filter(Boolean)}:null;}
function send(id,event,data){if(sockets[id])io.to(sockets[id]).emit(event,data)}
function broadcastParty(id){const p=parties[id];if(!p)return;for(const m of p.members)send(m,'partyUpdate',partyPayload(id))}
function queueCount(k){return queues[k].reduce((n,g)=>n+g.userIds.length,0)}
function queueState(){const o={};for(const league of Object.keys(LEAGUES)){o[league]={};for(const m of Object.keys(MODES))o[league][m]={unranked:queueCount(`${league}_${m}_unranked`),ranked:queueCount(`${league}_${m}_ranked`)};}return o}
function queueMembership(id){const out={};for(const league of Object.keys(LEAGUES))for(const m of Object.keys(MODES))for(const ranked of [false,true]){const k=`${league}_${m}_${ranked?'ranked':'unranked'}`;out[k]=queues[k].some(g=>g.userIds.includes(id));}return out}
function broadcastQueue(){io.emit('queueUpdate',queueState());for(const id of Object.keys(sockets))send(id,'queueMembership',queueMembership(id))}
function rankedAllowed(id,mode){return Number(users[id]?.stats?.[`unrankedMatches${mode}`]||0)>=3}
function detectPlatform(ua){return /Android|iPhone|iPad|iPod|Mobile|Windows Phone/i.test(String(ua||''))?'phone':'pc'}
function devicePlatformForUser(id){const sid=sockets[id];const s=sid&&io.sockets.sockets.get(sid);return detectPlatform(s?.handshake?.headers?.['user-agent']||'')}
function matchSafe(m,id){const u=safe(id);if(!u)return null;u.platform=m.platforms?.[id]||'phone';return u}
function findMatch(mode,ranked,league){const k=`${league}_${mode}_${ranked?'ranked':'unranked'}`, need=MODES[mode];let total=0,sel=[];for(const g of queues[k]){if(total+g.userIds.length<=need){sel.push(g);total+=g.userIds.length}if(total===need)break}if(total!==need)return null;const ids=sel.flatMap(g=>g.userIds);queues[k]=queues[k].filter(g=>!sel.includes(g));return ids}
function makeMatch(mode,ranked,league,ids){const shuffled=clone(ids).sort(()=>Math.random()-.5);const half=shuffled.length/2;const platforms=Object.fromEntries(ids.map(id=>[id,devicePlatformForUser(id)]));const match={id:rid('MATCH'),mode,ranked,league,platforms,participants:shuffled,teamT:shuffled.slice(0,half),teamCT:shuffled.slice(half),accepted:[],status:'waiting_accept',createdAt:Date.now(),mapVotes:{},roundVotes:{},screenshots:[],resolved:false};matches.push(match);persist();for(const id of ids)send(id,'matchFound',publicMatch(match));setTimeout(()=>timeoutMatch(match.id),20000);return match}
function publicMatch(m){return {matchId:m.id,id:m.id,mode:m.mode,ranked:m.ranked,league:m.league,leagueName:LEAGUES[m.league]||m.league,accepted:m.accepted.length,total:m.participants.length,timeout:Math.max(0,20-Math.floor((Date.now()-m.createdAt)/1000)),participants:m.participants.map(id=>matchSafe(m,id)).filter(Boolean)}}
function timeoutMatch(id){const m=matches.find(x=>x.id===id);if(!m||m.status!=='waiting_accept')return;m.status='cancelled';m.cancelReason='Не все игроки подтвердили матч за 20 секунд.';for(const u of m.participants)send(u,'matchCancelled',{matchId:id,reason:m.cancelReason});persist()}
function draftState(m){const d=m.draft;return {matchId:m.id,mode:m.mode,league:m.league,leagueName:LEAGUES[m.league]||m.league,participants:m.participants.map(id=>matchSafe(m,id)),totalParticipants:m.participants.length,totalSeconds:120,seconds:Math.max(0,Math.ceil((d.expiresAt-Date.now())/1000)),turnSeconds:15,currentCaptain:d.captains[d.turn],captains:d.captains.map(id=>matchSafe(m,id)),mapOptions:MAPS,remainingMaps:d.remainingMaps,mapBans:d.mapBans,roundOptions:ROUNDS,roundVotes:d.roundVotes,roundCounts:ROUNDS.reduce((o,r)=>(o[r]=Object.values(d.roundVotes).filter(v=>Number(v)===r).length,o),{}),chat:d.chat||[]}}
function broadcastDraft(m){for(const u of m.participants)send(u,'draftUpdate',draftState(m))}
function scheduleDraftTurn(m){if(m.status!=='draft'||m.draft.remainingMaps.length<=1)return;const token=++m.draft.turnToken;const matchId=m.id;setTimeout(()=>{const x=matches.find(v=>v.id===matchId);if(!x||x.status!=='draft'||x.draft.turnToken!==token)return;autoBan(m);},15000)}
function autoBan(m){if(m.status!=='draft')return;if(m.draft.remainingMaps.length<=1){finishDraft(m.id);return}const i=Math.floor(Math.random()*m.draft.remainingMaps.length);const map=m.draft.remainingMaps.splice(i,1)[0];m.draft.mapBans.push({map,userId:null,auto:true,timestamp:Date.now()});m.draft.turn=(m.draft.turn+1)%2;broadcastDraft(m);if(m.draft.remainingMaps.length<=1)finishDraft(m.id);else scheduleDraftTurn(m);persist()}
function startDraft(m){m.status='draft';const c=[m.teamT[Math.floor(Math.random()*m.teamT.length)],m.teamCT[Math.floor(Math.random()*m.teamCT.length)]];m.draft={captains:c,turn:0,mapBans:[],remainingMaps:MAPS.slice(),roundVotes:{},chat:[],expiresAt:Date.now()+120000,turnToken:0};for(const u of m.participants)send(u,'draftStart',draftState(m));scheduleDraftTurn(m);setTimeout(()=>{const x=matches.find(v=>v.id===m.id);if(x&&x.status==='draft')finishDraft(x.id,true)},120000);persist()}
function finishDraft(id,expired=false){const m=matches.find(x=>x.id===id);if(!m||m.status!=='draft')return;if(m.draft.remainingMaps.length>1){while(m.draft.remainingMaps.length>1){const i=Math.floor(Math.random()*m.draft.remainingMaps.length);const map=m.draft.remainingMaps.splice(i,1)[0];m.draft.mapBans.push({map,userId:null,auto:true,timestamp:Date.now()})}}m.map=m.draft.remainingMaps[0]||MAPS[0];m.hostCaptainId=m.draft.captains[Math.floor(Math.random()*m.draft.captains.length)]||m.participants[0];const counts=ROUNDS.map(r=>({r,n:Object.values(m.draft.roundVotes).filter(v=>Number(v)===r).length}));const max=Math.max(...counts.map(x=>x.n),0);const tied=counts.filter(x=>x.n===max).map(x=>x.r);m.rounds=tied[Math.floor(Math.random()*tied.length)]||8;m.maxMoney=16000;m.status='awaiting_result';m.captains=m.draft.captains;for(const u of m.participants)send(u,'draftFinished',{matchId:m.id,map:m.map,rounds:m.rounds,roundCounts:counts.reduce((o,x)=>(o[x.r]=x.n,o),{}),expired:!!expired});for(const u of m.participants)send(u,'matchLobby',lobby(m));persist()}
function lobby(m){const hostId=m.hostCaptainId||m.captains?.[0]||m.participants[0];return {matchId:m.id,mode:m.mode,ranked:m.ranked,league:m.league,leagueName:LEAGUES[m.league]||m.league,map:m.map,rounds:m.rounds,maxMoney:16000,captains:m.captains.map(id=>matchSafe(m,id)),hostCaptain:matchSafe(m,hostId),hostCaptainId:hostId,teamT:m.teamT.map(id=>matchSafe(m,id)),teamCT:m.teamCT.map(id=>matchSafe(m,id)),screenshots:m.screenshots}}
function resolve(m,winner,changes){if(m.resolved)return {ok:false,msg:'Матч уже обработан.'};if(!m.screenshots.length)return {ok:false,msg:'Нужен скриншот результата.'};if(!['T','CT'].includes(winner))return {ok:false,msg:'Неверная команда.'};for(const id of m.participants){const u=users[id];if(!u)continue;const won=(winner==='T'?m.teamT:m.teamCT).some(x=>x===id);const n=Number(changes?.[id]||0);const d=Number.isFinite(n)?Math.trunc(n):0;u.stats.matchHistory.unshift({matchId:m.id,mode:m.mode,ranked:m.ranked,map:m.map,rounds:m.rounds,winnerTeam:winner,won,eloDelta:d,eloAfter:0,timestamp:Date.now()});u.stats.matchHistory=u.stats.matchHistory.slice(0,100);recalcUserDerived(u,m.mode)}m.resolved=true;m.status='resolved';m.winnerTeam=winner;m.eloChanges=Object.fromEntries(m.participants.map(id=>[id,Number(changes?.[id]||0)]));m.resolvedAt=Date.now();for(const id of m.participants)send(id,'matchResolved',{matchId:m.id,winnerTeam:m.winnerTeam,eloChanges:m.eloChanges,league:m.league,leagueName:LEAGUES[m.league]||m.league,participants:m.participants.map(pid=>matchSafe(m,pid)),user:safe(id)});persist();return {ok:true}}

app.post('/api/register',async(req,res)=>{const {username,password,inGameNick,inGameId}=req.body||{};if(!username||!password||!inGameNick||!inGameId)return res.status(400).json({success:false,message:'Заполните все поля.'});if(Object.values(users).some(u=>u.username.toLowerCase()===String(username).trim().toLowerCase()))return res.status(409).json({success:false,message:'Такой логин уже занят.'});const id=uid();users[id]=normalize({username:String(username).trim(),password:hash(password),inGameNick:String(inGameNick).trim(),inGameId:String(inGameId).trim(),isAdmin:ADMIN_LOGINS.includes(String(username).trim().toLowerCase()),stats:stats(),friends:[],pendingRequests:[],createdAt:Date.now()});await persist();res.json({success:true,message:'Регистрация успешна. Теперь войдите.',user:safe(id)})});
app.post('/api/login',async(req,res)=>{const {username,password}=req.body||{};const e=Object.entries(users).find(([,u])=>u.username.toLowerCase()===String(username||'').trim().toLowerCase());if(!e||e[1].password!==hash(password))return res.status(401).json({success:false,message:'Неверный логин или пароль.'});normalize(e[1]);const bm=banMessage(e[1]);await persist();if(bm)return res.status(403).json({success:false,banned:true,message:bm});res.json({success:true,message:'Вход выполнен.',user:safe(e[0]),party:partyOf(e[0])?partyPayload(partyOf(e[0])[0]):null})});
app.get('/api/me',async(req,res)=>{const id=String(req.query.userId||'');const raw=users[id];if(!raw)return res.status(401).json({success:false,message:'Сессия недействительна.'});const bm=banMessage(raw);if(bm){await persist();if(sockets[id])disconnectUser(id,'accountBanned',{message:bm});return res.status(403).json({success:false,banned:true,message:bm})}const u=safe(id);const p=partyOf(id);res.json({success:true,user:u,party:p?partyPayload(p[0]):null});});
app.get('/api/user/:id',(req,res)=>{const u=safe(req.params.id);u?res.json({success:true,user:u}):res.status(404).json({success:false,message:'Игрок не найден.'})});
app.get('/api/search-users',(req,res)=>{const q=String(req.query.q||'').toLowerCase();res.json({success:true,users:Object.entries(users).filter(([id,u])=>id.includes(q)||u.username.toLowerCase().includes(q)||u.inGameNick.toLowerCase().includes(q)||u.inGameId.toLowerCase().includes(q)).slice(0,30).map(([id])=>safe(id))})});
app.post('/api/friend-request',async(req,res)=>{const {fromUserId,toUserId}=req.body;const a=users[fromUserId],b=users[toUserId];if(!a||!b||fromUserId===toUserId)return res.status(400).json({success:false,message:'Игрок не найден или указан неверно.'});if(a.friends.includes(toUserId))return res.status(400).json({success:false,message:'Вы уже друзья.'});if(!b.pendingRequests.includes(fromUserId))b.pendingRequests.push(fromUserId);await persist();send(toUserId,'friendRequest',{user:safe(fromUserId)});res.json({success:true})});
app.post('/api/friend-accept',async(req,res)=>{const {userId,friendId}=req.body;if(!users[userId]||!users[friendId])return res.status(404).json({success:false});users[userId].pendingRequests=users[userId].pendingRequests.filter(x=>x!==friendId);if(!users[userId].friends.includes(friendId))users[userId].friends.push(friendId);if(!users[friendId].friends.includes(userId))users[friendId].friends.push(userId);await persist();send(friendId,'friendChanged',{});res.json({success:true})});
app.post('/api/friend-reject',async(req,res)=>{const {userId,friendId}=req.body;if(users[userId])users[userId].pendingRequests=users[userId].pendingRequests.filter(x=>x!==friendId);await persist();res.json({success:true})});
app.get('/api/friends',(req,res)=>{const u=users[req.query.userId];if(!u)return res.status(404).json({success:false});res.json({success:true,friends:u.friends.map(safe).filter(Boolean),requests:u.pendingRequests.map(safe).filter(Boolean)})});
app.get('/api/private-messages',(req,res)=>{const id=String(req.query.userId||'');if(!users[id])return res.status(404).json({success:false,message:'Игрок не найден.'});res.json({success:true,messages:privateMessages.filter(m=>m.from===id||m.to===id).slice(-1000)})});
app.post('/api/create-party',async(req,res)=>{const {userId}=req.body;if(!users[userId])return res.status(404).json({success:false});const p=partyOf(userId);if(p)return res.json({success:false,party:partyPayload(p[0]),message:'Вы уже в пати.'});const id=rid('PARTY');parties[id]={code:id,leaderId:userId,members:[userId],createdAt:Date.now()};await persist();res.json({success:true,party:partyPayload(id)})});
app.post('/api/join-party',async(req,res)=>{const {userId,partyId}=req.body;const p=parties[partyId];if(!p)return res.status(404).json({success:false,message:'Пати не найдена.'});if(p.members.length>=5)return res.status(400).json({success:false,message:'Пати заполнена.'});if(!p.members.includes(userId))p.members.push(userId);await persist();broadcastParty(partyId);res.json({success:true,party:partyPayload(partyId)})});
app.post('/api/leave-party',async(req,res)=>{const {userId,partyId}=req.body;const p=parties[partyId];if(!p)return res.json({success:true});p.members=p.members.filter(x=>x!==userId);if(!p.members.length)delete parties[partyId];else{if(p.leaderId===userId)p.leaderId=p.members[0];broadcastParty(partyId)}await persist();res.json({success:true})});
app.post('/api/invite-party',async(req,res)=>{const {fromUserId,targetUserId}=req.body;const p=partyOf(fromUserId);if(!p)return res.status(400).json({success:false,message:'Сначала создайте пати.'});send(targetUserId,'partyInvite',{partyId:p[0],fromName:users[fromUserId]?.inGameNick||'Игрок'});res.json({success:true})});
app.post('/api/report',async(req,res)=>{
  const {reporterId,targetId,reason,matchId}=req.body;
  if(!users[reporterId]||!users[targetId])return res.status(404).json({success:false,message:'Игрок не найден.'});
  if(!['Токсичность','Читы','Багаюз'].includes(reason))return res.status(400).json({success:false,message:'Выберите причину.'});
  if(matchId){
    const m=matches.find(x=>x.id===matchId);
    if(!m||m.status!=='resolved'||!m.participants.includes(reporterId)||!m.participants.includes(targetId))return res.status(400).json({success:false,message:'Репорт по этому матчу доступен только после завершения матча.'});
    if(m.league!=='phone'||m.platforms?.[targetId]!=='pc')return res.status(400).json({success:false,message:'Этот тип репорта здесь недоступен.'});
  }else{
    const activePhonePcMatch=matches.find(m=>m.league==='phone'&&!['resolved','cancelled'].includes(m.status)&&m.participants.includes(targetId)&&m.platforms?.[targetId]==='pc');
    if(activePhonePcMatch)return res.status(400).json({success:false,message:'На PC-игрока в Phone лиге можно пожаловаться только после завершения матча.'});
  }
  const r={id:rid('REP'),reporterId,targetId,reason,matchId:matchId||null,status:'open',createdAt:Date.now()};
  reports.unshift(r);await persist();res.json({success:true,reportId:r.id})
});
app.post('/api/upload-avatar',upload.single('avatar'),async(req,res)=>{const u=users[req.body.userId];if(!u)return res.status(404).json({success:false});if(!req.file)return res.status(400).json({success:false,message:'Файл не выбран.'});if(!String(req.file.mimetype||'').startsWith('image/'))return res.status(400).json({success:false,message:'Можно загружать только изображения.'});const b64=req.file.buffer?req.file.buffer.toString('base64'):fs.readFileSync(req.file.path).toString('base64');u.stats.avatar=`data:${req.file.mimetype};base64,${b64}`;try{fs.unlinkSync(req.file.path)}catch{}await persist();send(req.body.userId,'userUpdated',safe(req.body.userId));res.json({success:true,avatar:u.stats.avatar})});
app.post('/api/change-nick',async(req,res)=>{const {userId,newNick}=req.body;if(!users[userId])return res.status(404).json({success:false});users[userId].inGameNick=String(newNick||'').trim().slice(0,32);await persist();res.json({success:true,user:safe(userId)})});
app.get('/api/top',(req,res)=>{const mode=MODES[req.query.mode]?req.query.mode:'1v1';res.json({success:true,users:Object.entries(users).map(([id])=>{const u=safe(id);return {...u,elo:u.stats[mode].elo,wins:u.stats[mode].wins,level:u.stats[mode].level}}).sort((a,b)=>b.elo-a.elo).slice(0,100)})});
app.post('/api/match/:id/screenshot',upload.single('screenshot'),async(req,res)=>{const m=matches.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({success:false,message:'Матч не найден.'});if(!m.participants.includes(req.body.userId))return res.status(403).json({success:false});if(!req.file)return res.status(400).json({success:false,message:'Скриншот не выбран.'});const s={id:rid('SHOT'),userId:req.body.userId,nickname:users[req.body.userId].inGameNick,url:'/uploads/'+req.file.filename,timestamp:Date.now()};m.screenshots.push(s);await persist();for(const u of m.participants)send(u,'screenshotAdded',{matchId:m.id,screenshot:s});res.json({success:true,screenshot:s})});
app.post('/api/match/:id/cancel-request',async(req,res)=>{const m=matches.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({success:false,message:'Матч не найден.'});const r={id:rid('CANCEL'),matchId:m.id,userId:req.body.userId,reason:String(req.body.reason||'Не могу зайти в игру').slice(0,300),status:'open',createdAt:Date.now()};cancelRequests.unshift(r);await persist();res.json({success:true,requestId:r.id})});
app.post('/api/admin/match/:id/cancel',async(req,res)=>{if(!isAdminUser(req.body.adminId))return res.status(403).json({success:false});const m=matches.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({success:false});if(m.status==='resolved'&&!resultEditAllowed(m))return res.status(400).json({success:false,message:'Окно изменения результата (3 часа) уже истекло.'});if(m.status==='resolved')rollbackResolvedResult(m);m.status='cancelled';m.cancelReason=String(req.body.reason||'Матч отменён администратором');for(const u of m.participants)send(u,'matchCancelled',{matchId:m.id,reason:m.cancelReason});await persist();res.json({success:true})});
app.post('/api/admin/cancel-request/:id',async(req,res)=>{if(!users[req.body.adminId]?.isAdmin)return res.status(403).json({success:false});const r=cancelRequests.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({success:false});r.status=req.body.status==='approved'?'approved':'rejected';if(r.status==='approved'){const m=matches.find(x=>x.id===r.matchId);if(m){m.status='cancelled';m.cancelReason='Отмена по заявке игрока, подтверждена администратором.';for(const u of m.participants)send(u,'matchCancelled',{matchId:m.id,reason:m.cancelReason})}}await persist();res.json({success:true})});
function isAdminUser(id){const u=users[id];return !!u&&(!!u.isAdmin||ADMIN_LOGINS.includes(String(u.username||'').toLowerCase()))}
function admin(req,res){if(!isAdminUser(req.query.adminId||req.body.adminId)){res.status(403).json({success:false,message:'Недостаточно прав.'});return null}return true}
app.get('/api/check-admin',(req,res)=>res.json({isAdmin:isAdminUser(req.query.userId)}));
app.get('/api/admin/stats',(req,res)=>{if(!admin(req,res))return;res.json({success:true,online:Object.keys(sockets).length,users:Object.keys(users).length,matches:matches.length,reports:reports.filter(x=>x.status==='open').length,cancelRequests:cancelRequests.filter(x=>x.status==='open').length})});
app.get('/api/admin/users',(req,res)=>{if(!admin(req,res))return;res.json({success:true,users:Object.entries(users).map(([id])=>safe(id))})});
app.get('/api/admin/reports',(req,res)=>{if(!admin(req,res))return;res.json({success:true,reports:reports.map(r=>({...r,reporter:safe(r.reporterId),target:safe(r.targetId)}))})});
app.get('/api/admin/cancel-requests',(req,res)=>{if(!admin(req,res))return;res.json({success:true,requests:cancelRequests.map(r=>({...r,user:safe(r.userId),match:matches.find(m=>m.id===r.matchId)}))})});
app.get('/api/admin/matches',(req,res)=>{if(!admin(req,res))return;res.json({success:true,matches:matches.filter(m=>m.status!=='cancelled'&&(m.status!=='resolved'||resultEditAllowed(m))).map(m=>({...m,participants:m.participants.map(id=>matchSafe(m,id)),teamT:m.teamT.map(id=>matchSafe(m,id)),teamCT:m.teamCT.map(id=>matchSafe(m,id))}))})});
app.post('/api/admin/report/:id',async(req,res)=>{if(!admin(req,res))return;const r=reports.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({success:false});r.status=req.body.status==='closed'?'closed':'open';r.adminId=req.body.adminId;await persist();res.json({success:true})});
app.post('/api/admin/match/:id/resolve',async(req,res)=>{if(!admin(req,res))return;const m=matches.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({success:false});let originalResolvedAt=null;if(m.resolved){if(!resultEditAllowed(m))return res.status(400).json({success:false,message:'Окно изменения результата (3 часа) уже истекло.'});originalResolvedAt=m.resolvedAt;rollbackResolvedResult(m)}m.status='awaiting_result';const r=resolve(m,req.body.winnerTeam,req.body.eloChanges||{});if(!r.ok)return res.status(400).json({success:false,message:r.msg});if(originalResolvedAt){m.resolvedAt=originalResolvedAt;await persist()}res.json({success:true,edited:!!originalResolvedAt})});
app.post('/api/admin/action',async(req,res)=>{if(!admin(req,res))return;const u=users[req.body.targetUserId];if(!u||u.isAdmin)return res.status(400).json({success:false,message:'Нельзя применить действие.'});const action=String(req.body.action||'');if(!['ban','mute','unban','unmute'].includes(action))return res.status(400).json({success:false,message:'Неизвестное действие.'});if(action==='unban'){delete u.ban;await persist();res.json({success:true});return}if(action==='unmute'){delete u.mute;await persist();res.json({success:true});return}const mins=Math.max(1,Math.min(525600,Number(req.body.minutes||0)));if(!Number.isFinite(mins))return res.status(400).json({success:false,message:'Неверный срок.'});const reason=String(req.body.reason||'').trim().slice(0,300);u[action==='ban'?'ban':'mute']={until:Date.now()+mins*60000,reason,issuedAt:Date.now(),adminId:req.body.adminId};await persist();if(action==='ban')disconnectUser(req.body.targetUserId,'accountBanned',{message:`Вы забанены на ${mins} мин. Причина: ${reason||'не указана'}`});else send(req.body.targetUserId,'chatBlocked',{message:`Вы получили мут на ${mins} мин. Причина: ${reason||'не указана'}`});res.json({success:true})});

io.on('connection',socket=>{socket.on('auth',id=>{if(!users[id])return;const bm=banMessage(users[id]);if(bm){socket.emit('accountBanned',{message:bm});return}sockets[id]=socket.id;socketUsers[socket.id]=id;send(id,'queueUpdate',queueState());send(id,'queueMembership',queueMembership(id));send(id,'chatHistory',chat.slice(-100));send(id,'privateHistory',privateMessages.filter(m=>m.from===id||m.to===id).slice(-1000));const p=partyOf(id);if(p)send(id,'partyUpdate',partyPayload(p[0]));for(const m of matches.filter(x=>x.participants.includes(id)&&!['resolved','cancelled'].includes(x.status))){if(m.status==='waiting_accept')send(id,'matchFound',publicMatch(m));if(m.status==='draft')send(id,'draftStart',draftState(m));if(m.status==='awaiting_result')send(id,'matchLobby',lobby(m));}});
socket.on('joinQueue',async({mode,ranked,partyId,league})=>{const id=socketUsers[socket.id];league=LEAGUES[league]?league:'phone';if(!id||!MODES[mode])return;const p=partyId&&parties[partyId]&&parties[partyId].members.includes(id)?parties[partyId]:null;const ids=p?p.members.slice():[id];if(ranked&&ids.some(x=>!rankedAllowed(x,mode))){send(id,'queueError',{message:`Нельзя играть в ранговый режим: сыграйте 3 обычных матча в режиме ${mode}.`});return}const k=`${league}_${mode}_${ranked?'ranked':'unranked'}`;if(!queues[k].some(g=>g.userIds.some(x=>ids.includes(x))))queues[k].push({userIds:ids,createdAt:Date.now(),league});broadcastQueue();const found=findMatch(mode,ranked,league);if(found)makeMatch(mode,ranked,league,found);broadcastQueue();await persist()});
socket.on('leaveQueue',async({mode,ranked,league})=>{const id=socketUsers[socket.id];league=LEAGUES[league]?league:'phone';if(!id)return;const k=`${league}_${mode}_${ranked?'ranked':'unranked'}`;queues[k]=queues[k].filter(g=>!g.userIds.includes(id));broadcastQueue();await persist()});
socket.on('acceptMatch',async({matchId})=>{const id=socketUsers[socket.id],m=matches.find(x=>x.id===matchId);if(!m||m.status!=='waiting_accept'||!m.participants.includes(id))return;if(!m.accepted.includes(id))m.accepted.push(id);for(const u of m.participants)send(u,'matchAcceptedUpdate',{matchId,accepted:m.accepted.length,total:m.participants.length});if(m.accepted.length===m.participants.length)startDraft(m);await persist()});
socket.on('declineMatch',async({matchId})=>{const id=socketUsers[socket.id],m=matches.find(x=>x.id===matchId);if(!m||!m.participants.includes(id))return;m.status='cancelled';m.cancelReason='Игрок отказался от матча.';for(const u of m.participants)send(u,'matchCancelled',{matchId,reason:m.cancelReason});await persist()});
socket.on('draftBan',async({matchId,map})=>{const id=socketUsers[socket.id],m=matches.find(x=>x.id===matchId);if(!m||m.status!=='draft'||!m.participants.includes(id))return;if(m.draft.captains[m.draft.turn]!==id)return;if(!m.draft.remainingMaps.includes(map))return;m.draft.remainingMaps=m.draft.remainingMaps.filter(x=>x!==map);m.draft.mapBans.push({map,userId:id,auto:false,timestamp:Date.now()});m.draft.turn=(m.draft.turn+1)%2;broadcastDraft(m);if(m.draft.remainingMaps.length<=1)finishDraft(matchId);else scheduleDraftTurn(m);await persist()});
socket.on('draftRoundVote',async({matchId,rounds})=>{const id=socketUsers[socket.id],m=matches.find(x=>x.id===matchId);const r=Number(rounds);if(!m||m.status!=='draft'||!m.participants.includes(id)||!ROUNDS.includes(r))return;m.draft.roundVotes[id]=r;broadcastDraft(m);await persist()});
socket.on('draftChat',async({matchId,text})=>{const id=socketUsers[socket.id],m=matches.find(x=>x.id===matchId);if(!m||m.status!=='draft'||!m.participants.includes(id))return;const mm=muteMessage(users[id]);if(mm){send(id,'chatBlocked',{message:mm});return}const t=String(text||'').trim().slice(0,300);if(!t)return;const msg={id:rid('DMSG'),userId:id,nickname:users[id].inGameNick,avatar:avatarValue(users[id]),text:t,timestamp:Date.now()};m.draft.chat.push(msg);m.draft.chat=m.draft.chat.slice(-200);for(const u of m.participants)send(u,'draftChat',msg);await persist()});
socket.on('partyInviteAccept',async({partyId})=>{const id=socketUsers[socket.id],p=parties[partyId];if(!id||!p||p.members.length>=5)return;if(!p.members.includes(id))p.members.push(id);await persist();broadcastParty(partyId)});
socket.on('chatMessage',async msg=>{const id=socketUsers[socket.id];if(!id)return;const mm=muteMessage(users[id]);if(mm){send(id,'chatBlocked',{message:mm});return}let text=typeof msg==='object'?(msg.text||''):String(msg||'');text=text.trim().slice(0,500);if(!text)return;const m={id:rid('MSG'),userId:id,nickname:users[id].inGameNick,avatar:users[id].stats.avatar,isAdmin:!!users[id].isAdmin,sticker:users[id].stats.sticker,text,timestamp:Date.now()};chat.push(m);chat=chat.slice(-500);io.emit('chatMessage',m);await persist()});
socket.on('privateMessage',async({toUserId,text})=>{const from=socketUsers[socket.id];if(!from||!users[toUserId])return;const mm=muteMessage(users[from]);if(mm){send(from,'chatBlocked',{message:mm});return}const m={id:rid('PM'),from,to:toUserId,text:String(text||'').trim().slice(0,500),timestamp:Date.now()};if(!m.text)return;privateMessages.push(m);privateMessages=privateMessages.slice(-1000);send(from,'privateMessage',m);send(toUserId,'privateMessage',m);await persist()});
socket.on('disconnect',()=>{const id=socketUsers[socket.id];if(id&&sockets[id]===socket.id)delete sockets[id];delete socketUsers[socket.id]})});
load().then(()=>server.listen(process.env.PORT||3000,()=>{console.log('Legend Pl server started');if(!process.env.DATABASE_URL)console.warn('DATABASE_URL is not set: Render ephemeral storage will not survive restarts. Set DATABASE_URL to Render PostgreSQL or DATA_DIR to a persistent disk.')}));


/* PLATFORM_LEAGUE_V4 */
function detectPlatformFromReq(req){
  const ua=String(req?.headers?.['user-agent']||'').toLowerCase();
  return /android|iphone|ipad|ipod|mobile|windows phone/.test(ua) ? 'phone' : 'pc';
}
function detectPlatformFromSocket(socket){
  const ua=String(socket?.handshake?.headers?.['user-agent']||'').toLowerCase();
  return /android|iphone|ipad|ipod|mobile|windows phone/.test(ua) ? 'phone' : 'pc';
}
function normalizeLeague(v){ return String(v||'pc').toLowerCase()==='phone' ? 'phone' : 'pc'; }
function leagueMatchesPlatform(league, platform){ return normalizeLeague(league)===normalizeLeague(platform); }

/* STRICT_LEAGUE_QUEUE_V5 */
function strictLeague(v){ return String(v||'pc').toLowerCase()==='phone' ? 'phone' : 'pc'; }
function actualPlatform(socket){
  const ua=String(socket?.handshake?.headers?.['user-agent']||'').toLowerCase();
  return /android|iphone|ipad|ipod|mobile|windows phone/.test(ua) ? 'phone' : 'pc';
}
function assertLeague(socket, league){
  const lg=strictLeague(league), pf=actualPlatform(socket);
  return lg===pf;
}
